from pathlib import Path

import torch

DEVICE = torch.device('cuda:0')

LOG_DIR = Path(__file__).parent.parent.parent / 'logs'

DATA_DIR = Path('/hdd1/home/soyuj/')
DEEP_IMPACT_DIR = DATA_DIR / 'deep-impact'

COLLECTION_PATH = DATA_DIR / 'expanded-collection.tsv'
CHECKPOINT_DIR = DATA_DIR / 'checkpoints'

BATCH_SIZE = 32

LLAMA_DIR = DATA_DIR / 'llama2'
LLAMA_HUGGINGFACE_CHECKPOINT = LLAMA_DIR / 'models_hf' / '7B'

INVERTED_INDEX_VOCAB = 'vocab.txt'
INVERTED_INDEX_INDEX = 'inverted_index.idx'
INVERTED_INDEX_DATA = 'inverted_index.dat'

IMPACT_SCORE_QUANTIZATION_BITS = 8
IMPACT_SCORE_FORMAT = 'B'
IMPACT_SCORE_BYTES = 1
DOC_ID_BYTES = 4
DOC_ID_FORMAT = 'I'
LOC_BYTES = 8
LOC_FORMAT = 'Q'

DOC_SCORE_BLOCK_BYTES = DOC_ID_BYTES + IMPACT_SCORE_BYTES
DOC_SCORE_BLOCK_FORMAT = DOC_ID_FORMAT + IMPACT_SCORE_FORMAT
LOC_BLOCK_BYTES = LOC_BYTES * 2
LOC_BLOCK_FORMAT = LOC_FORMAT * 2

COLLECTION_TYPES = ['msmarco', 'beir']

DEFAULT_TOP_K = 50
DEFAULT_TOP_P = 0.95
DEFAULT_MAX_NEW_TOKENS = 50
DEFAULT_MAX_TOKENS = 350
DEFAULT_NUM_RETURN_SEQUENCES = 80
